# Author: Green Mountain Systems AI Inc.
# Donated to IAB Tech Lab

"""Pydantic models for Campaign Automation data structures.

Covers pacing snapshots (Section 6.2) and ad server integration records
(Section 6.4) from the Campaign Automation Strategic Plan (ar-qt9).

bead: buyer-lna (Pacing snapshot storage)
bead: buyer-uoz (Ad server integration record storage)
"""

import uuid
from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Pacing Snapshot models (Section 6.2)
# ---------------------------------------------------------------------------


class RecommendationType(str, Enum):
    """Pacing recommendation types from the pacing engine."""

    REALLOCATE = "REALLOCATE"
    PAUSE = "PAUSE"
    INCREASE = "INCREASE"
    DECREASE = "DECREASE"
    FLAG = "FLAG"


class RecommendationStatus(str, Enum):
    """Status of a pacing recommendation."""

    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"


class ChannelSnapshot(BaseModel):
    """Per-channel breakdown within a pacing snapshot.

    Captures budget allocation, spend, and delivery metrics for a single
    channel (CTV, DISPLAY, AUDIO, etc.) at a point in time.
    """

    channel: str
    allocated_budget: float
    spend: float
    pacing_pct: float
    impressions: int = 0
    effective_cpm: float = 0.0
    fill_rate: float = 0.0


class DealSnapshot(BaseModel):
    """Per-deal breakdown within a pacing snapshot.

    Captures budget allocation, spend, and delivery metrics for a single
    deal at a point in time.
    """

    deal_id: str
    allocated_budget: float
    spend: float
    impressions: int = 0
    effective_cpm: float = 0.0
    fill_rate: float = 0.0
    win_rate: float = 0.0


class PacingRecommendation(BaseModel):
    """A pacing engine recommendation for budget reallocation or adjustment.

    Generated by the pacing engine when it detects deviation from the
    expected pacing curve.
    """

    type: RecommendationType
    source_channel: str | None = None
    target_channel: str | None = None
    amount: float | None = None
    reason: str = ""
    status: RecommendationStatus = RecommendationStatus.PENDING


class PacingSnapshot(BaseModel):
    """Campaign pacing state at a point in time.

    Created by the pacing engine at configurable intervals. Contains
    top-level campaign pacing data plus optional per-channel, per-deal
    breakdowns and engine recommendations.

    Maps to the pacing_snapshot table (Strategic Plan Section 6.2).
    """

    snapshot_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    campaign_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    total_budget: float
    total_spend: float
    pacing_pct: float
    expected_spend: float
    deviation_pct: float
    channel_snapshots: list[ChannelSnapshot] = Field(default_factory=list)
    deal_snapshots: list[DealSnapshot] = Field(default_factory=list)
    recommendations: list[PacingRecommendation] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Ad Server Integration models (Section 6.4)
# ---------------------------------------------------------------------------


class AdServerType(str, Enum):
    """Supported ad server platforms."""

    INNOVID = "INNOVID"
    FLASHTALKING = "FLASHTALKING"


class AdServerCampaignStatus(str, Enum):
    """Status of the ad server integration for a campaign."""

    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"


class BindingServingStatus(str, Enum):
    """Serving status of a deal-to-ad-server binding."""

    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ERROR = "ERROR"


class AdServerBinding(BaseModel):
    """Mapping between a deal/creative and an ad server line item.

    Each binding connects one deal + creative pair to a line item ID
    on the external ad server (Innovid or Flashtalking).
    """

    deal_id: str
    creative_id: str
    ad_server_line_id: str
    serving_status: BindingServingStatus = BindingServingStatus.ACTIVE
    last_sync_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class AdServerDelivery(BaseModel):
    """Delivery data reported by the ad server.

    Used for discrepancy detection between buyer-side and ad-server-side
    impression counts and spend.
    """

    impressions_served: int = 0
    spend_reported: float = 0.0
    last_report_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    discrepancy_pct: float = 0.0


class AdServerCampaign(BaseModel):
    """Ad server integration record for a campaign.

    Links a campaign to its representation on an external ad server
    (Innovid or Flashtalking). Contains deal-to-line-item bindings
    and aggregated delivery data.

    Maps to the ad_server_campaign table (Strategic Plan Section 6.4).
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    campaign_id: str
    ad_server: AdServerType
    ad_server_campaign_id: str
    status: AdServerCampaignStatus = AdServerCampaignStatus.PENDING
    bindings: list[AdServerBinding] = Field(default_factory=list)
    delivery: AdServerDelivery | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
