"""Publish the reference-seller's fixture creative images to a real, fetchable HTTPS URL.

    uv run python deploy_creative_fixtures.py            # dry run: lists what would upload
    uv run python deploy_creative_fixtures.py --apply

## Why this exists (U4/Part 1, Q6)

`get_creative_features`'s request schema (`creative/get-creative-features-request.json`) requires a
real `creative_manifest.assets.main_image.url` -- a fetchable HTTPS location, not a repo-relative
path. `handle_get_creative_features` on the reference governance agent fetches this URL over HTTPS
and evaluates the real bytes it gets back (dimension conformance, WCAG contrast, OCR text
extraction) -- there is no local-file code path, because a real submitted `creative_manifest` never
carries one either.

The four images themselves already exist and are checked into this package
(`fixtures/creatives/*.png`, generated by `gen_fixtures.py`, which also asserts their own contrast
properties before saving them). This script's only job is making them reachable at a real URL.

## Where this goes, and why the buyer's existing distribution rather than a new one

Reuses `agents/buyer/reference-buyer`'s existing CloudFront distribution/bucket -- the same
infrastructure `deploy_brand_json.py` and the governance agent's `deploy_jwks.py`/
`deploy_revocations.py` already publish `.well-known/*` documents to. No new AWS resources: this is
four small PNGs, and the buyer's distribution already has TLS, a stable domain, and the exact
403-to-index.html trap this script's own `verify_published` checks for, per those scripts' own
precedent.

Published under `.well-known/creatives/` (not `.well-known/` directly) since these are not
protocol-defined discovery documents like `brand.json`/`jwks.json` -- they are this unit's own fixture
assets, namespaced so they cannot collide with a real `.well-known` document a future unit adds.

## The CloudFront trap this script verifies rather than assumes

Same as `deploy_brand_json.py`/`deploy_jwks.py`: the distribution rewrites 403 to `index.html` for
SPA routing, so a missing object returns the UI's HTML with status 200, not a 404. A "the upload
returned no error" check would not catch a wrong key or a stale invalidation. This script fetches
each published URL afterward and asserts the content-type is a real image type, never `text/html`.
"""

from __future__ import annotations

from aws_region import region

import argparse
import hashlib
import sys
from pathlib import Path

import functools
import os

import boto3
import httpx

# The account comes from the credentials in use, not from a constant: this publishes into the buyer's
# UI bucket. Its name is `<instance-prefix>-buyer-agent-ui`: the prefix (an auto-generated unique
# id) supplies the S3 global uniqueness that the account+region suffix used to. Must match
# deploy_ui.py's BUCKET_NAME exactly, or fixtures publish to a bucket the UI never created.
REGION = region()

#: Instance prefix (see deploy_all.resolve_prefix). Defaults to 'adcp' (the original instance) for a
#: standalone run; deploy_all.py exports INSTANCE_PREFIX so orchestrated runs inherit the right one.
INSTANCE_PREFIX = os.environ.get("INSTANCE_PREFIX", "adcp").strip() or "adcp"


@functools.lru_cache(maxsize=1)
def account_id() -> str:
    return os.environ.get("AWS_ACCOUNT_ID", "").strip() or boto3.client(
        "sts"
    ).get_caller_identity()["Account"]


@functools.lru_cache(maxsize=1)
def bucket_name() -> str:
    return f"{INSTANCE_PREFIX}-buyer-agent-ui"


@functools.lru_cache(maxsize=1)
def _distribution() -> dict:
    """Whichever distribution fronts the buyer's UI bucket.

    Read off the distribution rather than recorded, so this cannot name a CloudFront domain from a
    different account than the bucket it is uploading to.
    """
    cloudfront = boto3.client("cloudfront", region_name=REGION)
    for page in cloudfront.get_paginator("list_distributions").paginate():
        for item in (page.get("DistributionList") or {}).get("Items") or []:
            origins = [o.get("DomainName", "") for o in item["Origins"]["Items"]]
            if any(bucket_name() in o for o in origins):
                return item
    raise SystemExit(
        f"No CloudFront distribution found in front of {bucket_name()}.\n"
        "  Create it first:  python3 deploy_all.py --only buyer-ui-origin"
    )


def published_root() -> str:
    return f"https://{_distribution()['DomainName']}"

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "creatives"
S3_PREFIX = ".well-known/creatives/"

#: (filename, content-type) -- all four are PNG per gen_fixtures.py's own `img.save(path, "PNG", ...)`.
FIXTURE_FILES: tuple[tuple[str, str], ...] = (
    ("clean_banner.png", "image/png"),
    ("urgency_claim_banner.png", "image/png"),
    ("low_contrast_banner.png", "image/png"),
    ("wrong_size_banner.png", "image/png"),
    # The `display_728x90` asset. A second evaluable format means the journey's Creative scan shows a
    # real verdict on more than one card.
    ("clean_leaderboard.png", "image/png"),
)

s3 = boto3.client("s3", region_name=REGION)
cloudfront = boto3.client("cloudfront", region_name=REGION)


def distribution_id() -> str:
    return _distribution()["Id"]


def published_url(filename: str) -> str:
    return f"{published_root()}/{S3_PREFIX}{filename}"


def verify_published(filename: str, expected_content_type: str) -> None:
    """Fetch what was actually published and check it is a real image, not the SPA's HTML.

    Uses httpx (already a project dependency via adcp) rather than stdlib urllib -- httpx verifies
    against the certifi bundle by default, same reasoning as `deploy_brand_json.py`'s own choice.
    """
    url = published_url(filename)
    response = httpx.get(url, timeout=15)
    content_type = response.headers.get("content-type", "")
    if not content_type.startswith("image/"):
        head = response.content[:80]
        raise SystemExit(
            f"{url} did not return an image (Content-Type: {content_type!r}). First bytes: {head!r}\n"
            "This is the CloudFront 403-to-index.html rewrite serving the UI, which means the object "
            "is not at the expected key."
        )
    print(f"  verified: {url} -> {content_type}, {len(response.content)} bytes")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    print(f"Fixtures directory: {FIXTURES_DIR}")
    missing = [name for name, _ in FIXTURE_FILES if not (FIXTURES_DIR / name).exists()]
    if missing:
        raise SystemExit(f"Missing fixture files, run gen_fixtures.py first: {missing}")

    print("\nWould publish:")
    for filename, content_type in FIXTURE_FILES:
        path = FIXTURES_DIR / filename
        print(f"  {path} -> s3://{bucket_name()}/{S3_PREFIX}{filename}  ({content_type})")
        print(f"    url: {published_url(filename)}")

    if not args.apply:
        print("\nDry run. Nothing uploaded.")
        return 0

    for filename, content_type in FIXTURE_FILES:
        path = FIXTURES_DIR / filename
        body = path.read_bytes()
        s3.put_object(
            Bucket=bucket_name(),
            Key=f"{S3_PREFIX}{filename}",
            Body=body,
            ContentType=content_type,
            # These are fixture assets, not something that rotates -- a longer cache than
            # brand.json/jwks.json's 300s is fine and reduces repeated fetches by the evaluator's own
            # per-process cache warming across container restarts.
            CacheControl="public, max-age=3600",
        )
        print(f"Uploaded {len(body)}B to s3://{bucket_name()}/{S3_PREFIX}{filename}")

    dist = distribution_id()
    paths = [f"/{S3_PREFIX}{filename}" for filename, _ in FIXTURE_FILES]
    caller_ref = hashlib.sha256("".join(paths).encode()).hexdigest()[:32]
    cloudfront.create_invalidation(
        DistributionId=dist,
        InvalidationBatch={
            "Paths": {"Quantity": len(paths), "Items": paths},
            "CallerReference": f"creative-fixtures-{caller_ref}",
        },
    )
    print(f"Invalidated {len(paths)} path(s) on distribution {dist}")

    print("\n=== Verifying what is actually served ===")
    for filename, content_type in FIXTURE_FILES:
        verify_published(filename, content_type)

    print("\nThe governance agent's get_creative_features evaluator fetches these URLs directly:")
    for filename, _ in FIXTURE_FILES:
        print(f"  {published_url(filename)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
